import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SettingsNav from "../_components/SettingsNav";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function SettingsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="text-[#0e0e0e] bg-[#fff] dark:bg-[#0e0e0e] dark:text-white ">
      <div className="flex gap-8">
        <SettingsNav />
        <main className="min-h-[calc(100vh-14rem-2px)] w-full md:w-[80%]">
          {children}
        </main>
      </div>
    </main>
  );
}
